Update capesaaPvtIP.sh
cape-sh/cape-ansible pull request #2
Opened 2021-01-12 06:05 UTC by aktaksh

for ubuntu apt install -y ansible git

2021-01-12 06:46 UTC, badoet commented on script/capesaaPvtIP.sh
> +apt install -y ansible git
add comments and change to apt install -y git ansible

2021-01-12 06:47 UTC, badoet requested changes
please edit

2021-01-12 08:50 UTC, aktaksh reviewed
rectified and comments added

2021-01-12 08:57 UTC, badoet approved these changes

2021-01-13 02:22 UTC, AndrewWhiteside approved these changes

2021-01-13 02:22 UTC, merged